# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b70bfa061a661e1065504971e5a2ec76a7c044f188407dfe76f42e9e04d312b7ab179be335ef954e1b57885fa197c3e7e7b0aaa19d39bc27795cbd81b92f7c

test:
  secret_key_base: f16b1f5898014f5ded3abb53f73dfa52d7e1ba35cacdff7185f2372368258b0cf644b6057c20f7d7611e951114cd2087b129441cb3b6b55d37bfc98aacf9ccbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
